name: pre-commit

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run lintcheck
